version: '2'
services:
  kennel-ws:
    container_name: kennel-ws
    build: .
    volumes:
      - "./bin/www:/src/bin/www"
    ports:
      - "443:443"
    depends_on:
      - "redis"
    environment:
      - PORT=443
      - DEBUG=*:*,-express:*
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis
    container_name: kennel-redis
    ports:
      - "6379:6379" #publish redis to local host as well as link to barcws
